### ISSUE TITLE
Unable to reproduce some results in table1 and table2

### ISSUE THREAD

**Issue by Ma-Yiming** [sehyunkwon/ICTC#4]
Great work! Learn a lot from it. However, I conducted experiments on three data sets: **stanford-40-actions, cifar10, and cifar100**, but **did not obtain the experimental results of table1 and table2 in the paper.**
I encountered the following problems during my experiments:
1. **Cluster names in step2b are unstable**
The results of the model summarizing **cluster names in step 2b were not consistent each time.**
![stanford-40-actions-step2b](https://github.com/sehyunkwon/ICTC/assets/60736178/c0d06412-ecc2-4149-9c6c-e57262147e33)
![cifar10-step2b](https://github.com/sehyunkwon/ICTC/assets/60736178/b7d08953-f571-460d-9e5f-15c284e01b89)
![cifar100-step2b](https://github.com/sehyunkwon/ICTC/assets/60736178/cb85b5f4-34de-456e-9b77-0cd7a37acc05)
I found that this has a significant impact on the performance of the model in step 3, such as the two different clusters of cifar10 in the figure above. 
  a. **Using the cluster names in cifar 10 test1**, the ACC of the final clustering result is **0.91** .
  b. **Using the cluster names in cifar10 test2**, the ACC of the final clustering result is **0.51**.

 2. **The output result of step3 does not match when calculating ACC**
I found that when cluster names are given, many of the answer output in step 3 do not belong to the cluster names in step 2b. This is very obvious in stanford-40-actions.
![stanford-40-actions-step3_](https://github.com/sehyunkwon/ICTC/assets/60736178/a8f4265e-0095-462e-8dc9-75b03f80f781)
For example, in the picture above, the places marked by the red box do not belong to the cluster names output by step2b, and this phenomenon will appear in large numbers in step3. So **my final calculated ACC on stanford-40-actions is only 0.13**。
3. **Does it require some manual optimization**
![refinement](https://github.com/sehyunkwon/ICTC/assets/60736178/815a569d-ff60-43b4-bac1-d11f50c3e3a1)
I would like to know whether the above-mentioned problems in step2b and step3 are due to the need for certain manual optimization, such as some rough manual selection of step2b or refinement in the picture above.

**Comment by rain305f** [comment]
!!!!!!!!!! I also meet the same question~ I cannot reproduct the results of table1 and table2 reported in the original paper. @sehyunkwon  Can the author provide the log or others to support the results of table1 and table2. I seriously suspect that some results may need to be processed manually.

**Comment by sehyunkwon** [comment]
Thanks for your attention! Our best results were obtained using the GPT-4 azure api version=2023-03-15-preview and the provided settings in GitHub repo and Appendix. In this settings, the results were stable. **Information about all the settings used, prompts, and all intermediate results are stored in `/ICTC/data/`**, please refer to it. I don't know the experimental settings you used, such as temperature, prompt, model, but I recommend you try to reproduce following our guidelines. If you can provide me the specific settings you used, I will be able to provide a more accurate response.

+1) If you are using a different api version or LLM model, prompt engineering may be necessary. Also, the form of the response may vary, so the process of post-processing the LLM's response may need to be adjusted. For example, remove ":", "," and other unnecessary words. Please check whether the responses are in the desired form and whether they have been correctly post-processed.

+2) In the Llama-2 experiments in Table 2, for stable results, we used gpt instead of llama only in step 2b. This comment will be added to the camera ready version.

+3) We also provide additional experiment settings and results using Llama-2 70B Chat HF (i.e., using only Llama-2 in all steps and not using gpt). We set 'do_sample=False' to allow fully reproducible results despite performance loss. Specific prompts and all intermediate results are stored in `/ICTC/data/llama_70b_chat_hf` for your reference.

**Comment by Ma-Yiming** [comment]
> Thanks for your attention! Our best results were obtained using the GPT-4 azure api version=2023-03-15-preview and the provided settings in GitHub repo and Appendix. In this settings, the results were stable. **Information about all the settings used, prompts, and all intermediate results are stored in `/ICTC/data/`**, please refer to it. I don't know the experimental settings you used, such as temperature, prompt, model, but I recommend you try to reproduce following our guidelines. If you can provide me the specific settings you used, I will be able to provide a more accurate response.
> 
> +1) If you are using a different api version or LLM model, prompt engineering may be necessary. Also, the form of the response may vary, so the process of post-processing the LLM's response may need to be adjusted. For example, remove ":", "," and other unnecessary words. Please check whether the responses are in the desired form and whether they have been correctly post-processed.
> 
> +2) In the Llama-2 experiments in Table 2, for stable results, we used gpt instead of llama only in step 2b. This comment will be added to the camera ready version.
> 
> +3) We also provide additional experiment settings and results using Llama-2 70B Chat HF (i.e., using only Llama-2 in all steps and not using gpt). We set 'do_sample=False' to allow fully reproducible results despite performance loss. Specific prompts and all intermediate results are stored in `/ICTC/data/llama_70b_chat_hf` for your reference.

Thank you for your reply!!! @sehyunkwon
According to your reply, I used GPT-4 azure api version=2023-03-15-preview and the default hyperparameters in utils/argument.py and prompts under /ICTC/data/ to reproduce from scratch. I got the following results on location and mood of stanford-40-actions:
![reproduction](https://github.com/sehyunkwon/ICTC/assets/60736178/dcf0b61a-e619-4b7c-89aa-9431d79cb72f)
In addition, the results of step2b are as follows:
![reproduction_step2b](https://github.com/sehyunkwon/ICTC/assets/60736178/0c52406c-0e0d-442d-9911-ca2fbe06e455)
I wonder if this is because the randomness of the large language model itself leads to unstable experimental results?

**Comment by sehyunkwon** [comment]
Sorry for late. Yes, since there is some randomness, we sometimes have to change the prompt (also depending on the version of the LLM). Since more language models have been released after the paper submission, it is expected that this issue will be alleviated over time.
