### ISSUE TITLE
PPMI Location (K=2) ground truth labels

### ISSUE THREAD

**Issue by agadetsky** [sehyunkwon/ICTC#7]
Dear authors,

Where can I find data and the ground truth labels for Location criterion of PPMI dataset?

With kind regards,
Artem

**Comment by sehyunkwon** [comment]
Hello Artem,

We manually human-labeled the indoor/outdoor for 700 PPMI images. However, since the PPMI images are not intended for location, a few images had unclear indoor/outdoor status. In such cases, the authors discussed and decided on the labels. Therefore, if the images were to be relabeled, the ground truth for these few images might change. For this reason, we have decided not to disclose the ground truth. We apologize for any inconvenience this may cause.

Sincerely,
Sehyun

**Comment by agadetsky** [comment]
@sehyunkwon Dear Sehyun,

Thank you for your prompt response. This makes sense. Could you please privately share with me the filenames and your human-labeled Location labels for these 700 PPMI images for research purposes only. My email is artem.gadetskii@epfl.ch

With kind regards,
Artem
