### ISSUE TITLE
Length and Detail of Text Condition

### ISSUE THREAD

**Issue by jwahnn** [sehyunkwon/ICTC#8]
Would a more detailed a long text condition give the users a better clustering result or would it make the performance worse? I am wondering of a situation where users might want to cluster on conditions that is not explainable in a single word or a phrase.

**Comment by sehyunkwon** [comment]
Thank you for your question. I believe that the longer the text criteria, the more it reduces ambiguity and increases specificity, thereby improving performance. (In this perspective, the existing clustering algorithm is a case where the length of the text criteria is 0.) However, since we are using an off-the-shelf LLM, it is important that this text criteria be written in a way that the LLM can easily understand. Thank you for your interesting question.

Sincerely,
Sehyun

**Comment by jwahnn** [comment]
Makes sense. Great work!
